defaults: &defaults
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

staging:
  <<: *defaults
  database: /var/www/sslapp_staging/shared/db/staging.sqlite3

production:
  <<: *defaults
  database: /var/www/sslapp_production/shared/db/production.sqlite3
